import { Lead, LeadSource, LeadStatus } from "@/lib/types/lead"

export const dummyLeads: Lead[] = [
  {
    id: "1",
    contact: {
      name: "John Doe",
      email: "john@example.com",
      phone: "+91 98765 43210",
      address: "Mumbai, Maharashtra",
    },
    source: LeadSource.WEBSITE,
    status: LeadStatus.NEW,
    budget: {
      min: 5000000,
      max: 7500000,
    },
    requirements: "3 BHK apartment in Andheri West",
    notes: "Looking for a property with good connectivity",
    assignedTo: "agent1",
    propertyPreferences: {
      type: ["apartment"],
      location: ["Andheri West", "Andheri East"],
      minBedrooms: 3,
      maxBedrooms: 3,
      minBathrooms: 2,
      maxBathrooms: 3,
      minArea: 1200,
      maxArea: 1500,
    },
    priority: "high",
    createdAt: "2024-01-01T10:00:00Z",
    updatedAt: "2024-01-01T10:00:00Z",
  },
  {
    id: "2",
    contact: {
      name: "Jane Smith",
      email: "jane@example.com",
      phone: "+91 98765 43211",
      address: "Pune, Maharashtra",
    },
    source: LeadSource.REFERRAL,
    status: LeadStatus.IN_PROGRESS,
    budget: {
      min: 10000000,
      max: 15000000,
    },
    requirements: "4 BHK villa in Koregaon Park",
    notes: "Prefers a corner plot with garden",
    assignedTo: "agent2",
    propertyPreferences: {
      type: ["villa"],
      location: ["Koregaon Park"],
      minBedrooms: 4,
      maxBedrooms: 4,
      minBathrooms: 3,
      maxBathrooms: 4,
      minArea: 2000,
      maxArea: 2500,
    },
    priority: "medium",
    createdAt: "2024-01-02T11:00:00Z",
    updatedAt: "2024-01-02T11:00:00Z",
  },
  {
    id: "3",
    contact: {
      name: "Raj Patel",
      email: "raj@example.com",
      phone: "+91 98765 43212",
      address: "Bangalore, Karnataka",
    },
    source: LeadSource.MAGIC_BRICKS,
    status: LeadStatus.FOLLOW_UP,
    budget: {
      min: 8000000,
      max: 12000000,
    },
    requirements: "2 BHK apartment in Indiranagar",
    notes: "Looking for a ready-to-move property",
    assignedTo: "agent3",
    propertyPreferences: {
      type: ["apartment"],
      location: ["Indiranagar", "Koramangala"],
      minBedrooms: 2,
      maxBedrooms: 2,
      minBathrooms: 2,
      maxBathrooms: 2,
      minArea: 1000,
      maxArea: 1200,
    },
    priority: "low",
    createdAt: "2024-01-03T12:00:00Z",
    updatedAt: "2024-01-03T12:00:00Z",
  },
] 