import { Property } from '@/lib/types/property';

export const dummyProperties: Property[] = [
  {
    id: '1',
    title: 'Luxury Apartment in City Center',
    description: 'Beautiful 3BHK apartment with modern amenities and great city views.',
    type: 'apartment',
    category: 'residential',
    status: 'available',
    listingType: 'sale',
    location: {
      address: '123 Park Avenue',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400001',
      latitude: 19.0760,
      longitude: 72.8777,
    },
    specifications: {
      bedrooms: 3,
      bathrooms: 2,
      balconies: 1,
      totalFloors: 20,
      floorNumber: 15,
      furnishing: 'fully-furnished',
      superBuiltupArea: 1500,
      carpetArea: 1200,
      parking: 2,
      ageOfProperty: 2,
      availableFrom: '2024-02-01',
    },
    pricing: {
      price: 25000000,
      pricePerSqFt: 16666,
      maintenanceCharges: 10000,
      bookingAmount: 500000,
      currency: 'INR',
      negotiable: true,
    },
    amenities: [
      { id: '1', name: '24/7 Security', category: 'security', icon: 'shield' },
      { id: '2', name: 'Swimming Pool', category: 'leisure', icon: 'pool' },
      { id: '3', name: 'Gym', category: 'sports', icon: 'dumbbell' },
    ],
    images: [
      {
        id: '1',
        url: '/dummy/property-1-main.jpg',
        alt: 'Living Room',
        isPrimary: true,
      },
      {
        id: '2',
        url: '/dummy/property-1-2.jpg',
        alt: 'Kitchen',
      },
    ],
    assignedTo: '1', // Team member ID
    createdAt: '2024-01-01T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
    publishedAt: '2024-01-01T12:00:00Z',
    featured: true,
    verified: true,
    tags: ['premium', 'city-view', 'high-floor'],
  },
  {
    id: '2',
    title: 'Commercial Office Space',
    description: 'Prime office space in business district with modern infrastructure.',
    type: 'office',
    category: 'commercial',
    status: 'available',
    listingType: 'rent',
    location: {
      address: '456 Business Park',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      pincode: '400051',
      latitude: 19.0178,
      longitude: 72.8478,
    },
    specifications: {
      totalFloors: 12,
      floorNumber: 8,
      furnishing: 'semi-furnished',
      superBuiltupArea: 2000,
      carpetArea: 1800,
      parking: 4,
      ageOfProperty: 1,
      availableFrom: '2024-01-15',
    },
    pricing: {
      price: 200000,
      pricePerSqFt: 100,
      maintenanceCharges: 20000,
      currency: 'INR',
      negotiable: true,
    },
    amenities: [
      { id: '4', name: '24/7 Access', category: 'security', icon: 'key' },
      { id: '5', name: 'Conference Room', category: 'convenience', icon: 'users' },
      { id: '6', name: 'Cafeteria', category: 'convenience', icon: 'coffee' },
    ],
    images: [
      {
        id: '3',
        url: '/dummy/property-2-main.jpg',
        alt: 'Office Space',
        isPrimary: true,
      },
      {
        id: '4',
        url: '/dummy/property-2-2.jpg',
        alt: 'Conference Room',
      },
    ],
    assignedTo: '2',
    createdAt: '2024-01-02T10:00:00Z',
    updatedAt: '2024-01-02T10:00:00Z',
    publishedAt: '2024-01-02T14:00:00Z',
    featured: false,
    verified: true,
    tags: ['commercial', 'business-district', 'modern'],
  },
]; 