import { TeamMember } from '@/lib/types/team';

export const dummyTeamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@propdekho.com',
    phone: '+91 98765 43210',
    role: 'admin',
    department: 'management',
    status: 'active',
    permissions: {
      canManageTeam: true,
      canManageLeads: true,
      canManageProperties: true,
      canViewReports: true,
      canManageSettings: true,
      canDeleteRecords: true,
      canExportData: true,
    },
    stats: {
      totalLeads: 150,
      activeLeads: 45,
      closedDeals: 85,
      conversionRate: 56.67,
      lastActivityAt: '2024-01-15T14:30:00Z',
    },
    avatar: '/avatars/rajesh.jpg',
    title: 'Senior Sales Manager',
    bio: 'Experienced real estate professional with over 10 years in the industry',
    joinedAt: '2023-01-01T00:00:00Z',
    lastLoginAt: '2024-01-15T14:30:00Z',
    createdAt: '2023-01-01T00:00:00Z',
    updatedAt: '2024-01-15T14:30:00Z',
    subordinates: ['4', '5', '6'],
    tags: ['top-performer', 'mentor'],
  },
  {
    id: '2',
    name: 'Priya Sharma',
    email: 'priya.sharma@propdekho.com',
    phone: '+91 98765 43211',
    role: 'manager',
    department: 'sales',
    status: 'active',
    permissions: {
      canManageTeam: true,
      canManageLeads: true,
      canManageProperties: true,
      canViewReports: true,
      canManageSettings: false,
      canDeleteRecords: false,
      canExportData: true,
    },
    stats: {
      totalLeads: 120,
      activeLeads: 35,
      closedDeals: 65,
      conversionRate: 54.17,
      lastActivityAt: '2024-01-15T13:45:00Z',
    },
    avatar: '/avatars/priya.jpg',
    title: 'Sales Team Lead',
    bio: 'Passionate about helping clients find their dream properties',
    joinedAt: '2023-02-01T00:00:00Z',
    lastLoginAt: '2024-01-15T13:45:00Z',
    createdAt: '2023-02-01T00:00:00Z',
    updatedAt: '2024-01-15T13:45:00Z',
    supervisor: '1',
    subordinates: ['7', '8'],
    tags: ['sales-expert'],
  },
  {
    id: '3',
    name: 'Amit Patel',
    email: 'amit.patel@propdekho.com',
    phone: '+91 98765 43212',
    role: 'agent',
    department: 'sales',
    status: 'active',
    permissions: {
      canManageTeam: false,
      canManageLeads: true,
      canManageProperties: true,
      canViewReports: false,
      canManageSettings: false,
      canDeleteRecords: false,
      canExportData: false,
    },
    stats: {
      totalLeads: 80,
      activeLeads: 25,
      closedDeals: 40,
      conversionRate: 50.00,
      lastActivityAt: '2024-01-15T12:15:00Z',
    },
    avatar: '/avatars/amit.jpg',
    title: 'Real Estate Agent',
    bio: 'Specialized in luxury residential properties',
    joinedAt: '2023-03-01T00:00:00Z',
    lastLoginAt: '2024-01-15T12:15:00Z',
    createdAt: '2023-03-01T00:00:00Z',
    updatedAt: '2024-01-15T12:15:00Z',
    supervisor: '2',
    tags: ['luxury-specialist'],
  },
  {
    id: '4',
    name: 'Sarah Khan',
    email: 'sarah.khan@propdekho.com',
    phone: '+91 98765 43213',
    role: 'support',
    department: 'support',
    status: 'active',
    permissions: {
      canManageTeam: false,
      canManageLeads: true,
      canManageProperties: false,
      canViewReports: false,
      canManageSettings: false,
      canDeleteRecords: false,
      canExportData: false,
    },
    stats: {
      totalLeads: 200,
      activeLeads: 50,
      closedDeals: 0,
      conversionRate: 0,
      lastActivityAt: '2024-01-15T11:30:00Z',
    },
    avatar: '/avatars/sarah.jpg',
    title: 'Customer Support Specialist',
    bio: 'Dedicated to providing excellent customer service',
    joinedAt: '2023-04-01T00:00:00Z',
    lastLoginAt: '2024-01-15T11:30:00Z',
    createdAt: '2023-04-01T00:00:00Z',
    updatedAt: '2024-01-15T11:30:00Z',
    supervisor: '1',
    tags: ['customer-focused'],
  },
]; 